package com.example.dagger_2.sample_project.di

import android.content.Context
import androidx.room.Room
import com.example.dagger_2.sample_project.db.FakerDB
import dagger.Module
import dagger.Provides
import javax.inject.Singleton

@Module
class DatabaseModule {

    /**
     *Since the database object is generated by Builder pattern, we can't inject directly,
     * Hence we are generating manually using Dagger inside Database module
     *
     * Since it requires Context to create the object,
     * and Component is responsible to pass the Context and we need to change the Component accordingly
     */
    @Singleton
    @Provides
    fun provideFakerDB(context: Context): FakerDB {
        return Room.databaseBuilder(context, FakerDB::class.java, "FAKER_DB").build()
    }
}